import { Inter } from "next/font/google";
import "@/assets/css/bootstrap.min.css";
import "@/assets/css/animate.min.css";

import "@/assets/css/nice-select.min.css";
import "@/assets/css/magnific.min.css";
import "@/assets/css/slick.min.css";

import "@/assets/css/responsive.css";
import "@/assets/css/style.css";
import Script from "next/script";
import Header from "@/componenets/Header";
import Footer from "@/componenets/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LemartSoft - IT Solutions & Technology",
  description: "Generated by create next app",
  charset: "UTF-8",
  name: "viewport",
  content: "width=device-width, initial-scale=1.0",
  httpEquiv: "X-UA-Compatible",
  content: "IE=edge",
  content: "ie=edge",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        <div className="back-to-top">
          <span className="back-top">
            <i className="fa fa-angle-up"></i>
          </span>
        </div>

        <Script src="https://www.google.com/recaptcha/api.js" async defer />
        
        <Script src="js/jquery.min.js" />
        <Script src="js/bootstrap.min.js" />
        <Script src="js/fontawesome.min.js" />
        <Script src="js/magnific.min.js" />
        <Script src="js/nice-select.min.js" />
        <Script src="js/slick.min.js" />
        <Script src="js/owl.min.js" />
        <Script src="js/counter-up.min.js" />
        <Script src="js/waypoint.min.js" />
        <Script src="js/wow.min.js" />
        <Script src="js/main.js" />
      </body>
    </html>
  );
}
